version: '3.2'

services:

    www-database:
        image: wuaiwow/www-database
        build:
            context: .
            dockerfile: ./deployment/docker/database/Dockerfile
        networks:
            - www-network
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password2
        volumes:
            - ./volume/var/lib/mysql:/var/lib/mysql

    www-server:
        stdin_open: true
        tty: true
        image: wuaiwow/www-server
        build:
            context: .
            dockerfile: ./deployment/docker/www/Dockerfile
        networks:
            - www-network
        depends_on:
            - www-database

networks:
    www-network:
