version: '3.2'

services:
    www-database:
        image: wuaiwow/www-database
        networks:
            - www-network
        ports:
            - 3309:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password2
        volumes:
            - ./volume/var/lib/mysql:/var/lib/mysql
            - ./volume/backup:/www/wuaiwow-www/backup
            # - ./database/:/docker-entrypoint-initdb.d/schema.sql:ro
    www-server:
        image: wuaiwow/www-server
        networks:
            - www-network
        ports:
            - 80:8080
        depends_on:
            - www-database
        command: ["wait-for-it.sh", "-t", "90", "www-database:3306", "--", "docker-entrypoint.sh", "supervisord"]

networks:
    www-network:
